version: 0.2

env:
  variables:
    MONGODB_URI: 'mongodb+srv://gapchat:d52zU0DtSVjWtvMA@gapchat-cluster-6ceay:mongodb:net/GapChatDB?retryWrites=true&w=majority'
    PORT: 80

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
artifacts:
  files:
    - '**/*'
